Repository openshift/kubernetes-kubectl, pull requests merged in 2020-01, with the labels that each got.

#9 UPSTREAM: 86693: silence usage when pass bad cmd options
  pkg/util/templates/templater.go
Labels: lgtm, size/XS

#10 UPSTREAM: <carry>: kubectl: allow --config and --kubeconfig
  pkg/cmd/config/config.go
Labels: approved, lgtm, size/XS

#11 UPSTREAM: <carry>: kubectl: allow --config and --kubeconfig
  pkg/cmd/config/config.go
Labels: approved, lgtm, size/XS

#12 UPSTREAM: 85490: don't error if set-resources patch is empty
  pkg/cmd/set/set_resources.go
  pkg/cmd/set/set_subject.go
Labels: lgtm

#13 UPSTREAM: 87152: Allow embedding logs command
  pkg/cmd/logs/logs.go
Labels: lgtm, size/XS

#14 UPSTREAM: <carry>: kubectl: allow --config and --kubeconfig
  pkg/cmd/config/config.go
Labels: lgtm, size/XS
